
import React, { useState } from "react";
import BlurredCard from "./ui/BlurredCard";
import { ChevronDown, ChevronUp, HelpCircle } from "lucide-react";

const faqs = [
  {
    question: "What is Pharma Research Pro?",
    answer: "Pharma Research Pro is a specialized AI tool designed to support pharmaceutical research and clinical trial processes. It offers advanced data analysis, comprehensive literature reviews, and predictive insights for drug development and testing."
  },
  {
    question: "How does Pharmaceutical Assistant GPT differ from Pharma Research Pro?",
    answer: "While Pharma Research Pro focuses on research and clinical trials, Pharmaceutical Assistant GPT specializes in medication management, scheduling, and interaction checks for healthcare professionals and patients."
  },
  {
    question: "Is my data secure when using these AI tools?",
    answer: "Yes, we prioritize user privacy and data security, especially when handling sensitive health information. Our tools comply with relevant data protection regulations and implement robust security measures."
  },
  {
    question: "Can these tools replace pharmacists or pharmaceutical researchers?",
    answer: "No, our AI tools are designed to assist and enhance the work of pharmaceutical professionals, not replace them. They provide support by automating routine tasks and offering data-driven insights, but human expertise and judgment remain essential."
  },
  {
    question: "How accurate are the drug interaction predictions?",
    answer: "Our drug interaction predictions are based on comprehensive databases and AI algorithms. However, they should be used as a reference tool alongside professional judgment. Always consult with healthcare providers for medical decisions."
  },
  {
    question: "Can I export reports and analyses generated by these tools?",
    answer: "Yes, both Pharma Research Pro and Pharmaceutical Assistant GPT offer export capabilities for reports, analyses, and medication schedules in various formats for easy integration into your workflow."
  }
];

const FaqSection = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  
  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };
  
  return (
    <section className="py-20 relative overflow-hidden" id="faq">
      <div className="absolute inset-0 bg-grid opacity-20 -z-10"></div>
      
      <div className="container mx-auto px-6 md:px-12">
        <div className="max-w-3xl mx-auto text-center mb-16 reveal">
          <div className="inline-flex items-center justify-center px-3 py-1 mb-6 border border-cyber-blue/30 rounded-full bg-cyber-blue/10 backdrop-blur-sm">
            <HelpCircle className="w-4 h-4 mr-2 text-cyber-blue" />
            <span className="text-sm">Got Questions?</span>
          </div>
          
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            Frequently Asked Questions
          </h2>
          
          <p className="text-lg text-muted-foreground">
            Find answers to common questions about our pharmaceutical AI tools and their capabilities.
          </p>
        </div>
        
        <div className="max-w-4xl mx-auto reveal">
          <BlurredCard className="divide-y divide-white/5">
            {faqs.map((faq, index) => (
              <div key={index} className="py-5 first:pt-0 last:pb-0">
                <button
                  className="flex justify-between items-center w-full text-left"
                  onClick={() => toggleFaq(index)}
                >
                  <h3 className="text-lg font-medium">{faq.question}</h3>
                  {openIndex === index ? (
                    <ChevronUp className="w-5 h-5 text-cyber-blue flex-shrink-0" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-cyber-blue flex-shrink-0" />
                  )}
                </button>
                
                <div 
                  className={`mt-2 text-muted-foreground overflow-hidden transition-all duration-300 ${
                    openIndex === index ? "max-h-96 opacity-100" : "max-h-0 opacity-0"
                  }`}
                >
                  <p>{faq.answer}</p>
                </div>
              </div>
            ))}
          </BlurredCard>
        </div>
      </div>
    </section>
  );
};

export default FaqSection;
